# Generated by Django 3.0.7 on 2020-06-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actnaturalapp', '0007_auto_20200612_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
