# Generated by Django 3.0.7 on 2020-06-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actnaturalapp', '0008_auto_20200612_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/'),
        ),
    ]
