# Generated by Django 3.0.7 on 2020-06-16 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actnaturalapp', '0013_auto_20200615_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='actnaturalapp.Team'),
            preserve_default=False,
        ),
    ]
