# Generated by Django 3.0.7 on 2020-06-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actnaturalapp', '0014_species_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichmentitem',
            name='note',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
