# Generated by Django 3.0.7 on 2020-06-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actnaturalapp', '0015_auto_20200616_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichmenttype',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='actnaturalapp.Team'),
            preserve_default=False,
        ),
    ]
