# Generated by Django 3.0.7 on 2020-06-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actnaturalapp', '0016_enrichmenttype_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichmentlogentry',
            name='note',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
