# Generated by Django 3.0.7 on 2020-06-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actnaturalapp', '0017_auto_20200618_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrichmentlogentry',
            options={'ordering': ('date',), 'verbose_name': 'EnrichmentLogEntry', 'verbose_name_plural': 'EnrichmentLogEntries'},
        ),
    ]
