# Generated by Django 3.0.7 on 2020-06-18 16:37

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('actnaturalapp', '0018_auto_20200618_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrichmentlogentry',
            options={'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('date'), descending=True),), 'verbose_name': 'EnrichmentLogEntry', 'verbose_name_plural': 'EnrichmentLogEntries'},
        ),
    ]
