# Generated by Django 3.0.7 on 2020-06-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actnaturalapp', '0019_auto_20200618_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrichmentlogentry',
            options={'verbose_name': 'EnrichmentLogEntry', 'verbose_name_plural': 'EnrichmentLogEntries'},
        ),
    ]
