# Generated by Django 3.0.7 on 2020-06-19 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actnaturalapp', '0022_auto_20200619_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichmentlogentry',
            name='enrichment_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actnaturalapp.EnrichmentItem'),
        ),
    ]
