# Generated by Django 3.0.7 on 2020-06-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actnaturalapp', '0023_auto_20200619_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrichmentitem',
            name='is_manager_approved',
        ),
        migrations.RemoveField(
            model_name='enrichmentitem',
            name='is_vet_approved',
        ),
        migrations.AddField(
            model_name='animalenrichmentitem',
            name='is_manager_approved',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animalenrichmentitem',
            name='is_vet_approved',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
